### ISSUE TITLE
Bootloader info

### ISSUE THREAD

**Issue by folny** [knielsen/stm32f4_wireless_bootloader#1]
Hi

How to use this bootloader ? is there any other application that transfers binaries to this bootloader ?.

**Comment by knielsen** [comment]
The application to transfer binaries to the bootloader is here:

  https://github.com/knielsen/tiva_wireless_bootloader/blob/master/wireless-flash.pl

Usage is like this:

  perl wireless_bootloader/wireless-flash.pl -t /dev/ttyACM1 ledtorus.bin

This talks to a microcontroller board connected on the /dev/ttyACM1 usb<->serial port, which then talks wirelessly via two nRF24L01+ radio modules to the target bootloader.

All of the required source code and PCB layouts are in various repositories on my github.

If you want to look deeper I'll dig up the links to everything that's needed. I'm not sure if this is what you are after. This is made for a few custom applications, so only has the required functionality for these. And this is using the nRF24L01+ radio protocol, not consumer wifi.

**Comment by folny** [comment]
Thank you for your answer, I'm looking for a bootloader that would work with the STM32G4 series that I want to use in my project and NRF24L01. It would be great if it was a simple application for Windows that your bootloader could use.

**Comment by knielsen** [comment]
Right, I think the code can be used for that, but it will probably need some modifications. The code as written is for STM32F4, haven't tried STM32G4 yet to know what the differences are.

The application for the computer is just a simple command-line Perl script that accesses the serial port, that should be easy to use on Windows I assume (I don't use Windows myself).

The computer needs to be connected to a microcontroller board running this code: https://github.com/knielsen/pov_sender . This is the part sending the binaries to the target. For historical reason this code is written to run not on STM32, but on Texas Instruments Tiva TM4C, eg. their Tiva Launchpad. Or you could port it to another microcontroller of course.

As I wrote, this was written as an internal tool, so it doesn't have any general-purpose polishing. The functionality is there but it will need modifications to be used in other projects.

Feel free to ask if you have more questions!

 - Kristian.

**Comment by folny** [comment]
Thank you for the quick answer, I don't have a Tiva TM4C microcontroller at home and I don't even use them so I can't even try this code https://github.com/knielsen/pov_sender do you think it would be a big problem for you to modify this code to work on the STM32F103 (Bluepill) microcontroller ? it also has a USB VCP. I feel that it would take me a very long time because I still have little experience.

**Comment by knielsen** [comment]
Unfortunately I do not have plans to develop further on the code at this point.
